repos:
  - repo: local
    hooks:
      - id: test
        name: Test all test cases
        entry: bash test.sh
        language: system
        types: [file]
        files: \.(sh|bats)$
        pass_filenames: false
      - id: gen-doc
        name: Generate documentation
        entry: bash doc.sh
        language: system
        types: [file]
        files: \.(sh|bats)$
        pass_filenames: false
